import { Geist, Geist_Mono } from "next/font/google";
import MainNavbar from "@/shared/components/layouts/header/navbar/MainNavbar";
import Footer from "@/shared/components/layouts/footer/Footer";
import ContactDrawer from "@/shared/components/ui/ContactDrawer";
import Providers from "@/store/providers";

import "@mantine/core/styles.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prixa Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <MainNavbar />
          <ContactDrawer />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
